### ISSUE TITLE
Docker image segfault

### ISSUE THREAD

**Issue by bretello** [tmate-io/tmate-slave#104]
Hello and thanks for this wonderful project.

I've been receiving reports of clients receiving the following error when connecting to a tmate instance:
```server version is too old for client```

Since the [docker image](https://hub.docker.com/r/tmate/tmate-ssh-server) hasn't been updated in ~2 years, I decided to build it myself, but building `master` resulted in the container image immediately crashing on startup with no info being printed.

Digging a bit with `gdb` results in the following stack trace 

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f6eb319a77d in getframeaddr () from /usr/lib/libexecinfo.so.1
(gdb) bt
#0  0x00007f6eb319a77d in getframeaddr () from /usr/lib/libexecinfo.so.1
#1  0x00007f6eb319a971 in backtrace () from /usr/lib/libexecinfo.so.1
#2  0x000055e2a25f60c1 in tmate_preload_trace_lib () at tmate-debug.c:109
#3  0x000055e2a25c1315 in main (argc=<optimized out>, argv=0x7ffccc1b1108, envp=0x7ffccc1b1128) at tmate-main.c:172 
```

**Comment by gxanshu** [comment]
any updates, getting same error

**Comment by bretello** [comment]
I moved over to https://github.com/owenthereal/upterm since this project isn't active anymore and it's pretty hard to maintain
